FROM ollama/ollama:latest

EXPOSE 11434

WORKDIR /root

HEALTHCHECK --interval=10s --timeout=5s --start-period=30s --retries=3 \
  CMD curl -f http://localhost:11434/api/tags || exit 1

CMD ["serve"]
